services:

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: instituicao_academica
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    networks:
      - rede-interna

  backend:
    build:
      context: ./sistemagestaoacademica
    environment:
      DB_HOST: postgres
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_SENHA: ${ADMIN_SENHA}
    depends_on:
      - postgres
    networks:
      - rede-interna

  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - rede-interna

networks:
  rede-interna:
    driver: bridge