spring.application.name=sistemagestaoacademica
spring.datasource.url=jdbc:postgresql://${DB_HOST}/instituicao_academica
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
hibernate.dialect=org.hibernate.dialect.HSQLDialect

jwt.secret=${JWT_SECRET}
jwt.expiration=86400000

admin.email=${ADMIN_EMAIL}
admin.senha=${ADMIN_SENHA}

spring.jpa.hibernate.ddl-auto=create-drop
